In [1]:
import numpy as np

In [2]:
x=[[1,2,3],[4,5,6],[7,8,1]]

In [3]:
x

[[1, 2, 3], [4, 5, 6], [7, 8, 1]]

In [6]:
arr= np.array(x)

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1]])

In [9]:
arr.sum(axis = 0)

array([12, 15, 10])

In [10]:
arr.sum(axis = 1)

array([ 6, 15, 16])

In [15]:
arr.size

9